import Head from "next/head";
import styles from '@/styles/Home.module.css'
export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.home}>
          <h1>Hunting Coder</h1>
          {/* <Image src='/home.png' width={202} height={132} style={{borderRadius:'10px'}}/> */}
          <img src='/home.png' width={202} height={132} className={styles.img}/>
          <h1>Top Blogs</h1>
          <div className="topblogs">
            <div className="topblog">
              <h1 style={{color:"brown"}}>blog1 is here</h1>
              <p style={{fontSize:'20px'}}>This is blog1</p>
              <button className={styles.btn}>read more</button>
            </div>
            <div className="topblog">
              <h1 style={{color:"brown"}}>blog1 is here</h1>
              <p style={{fontSize:'20px'}}>This is blog1</p>
              <button className={styles.btn}>read more</button>
            </div>
            <div className="topblog">
              <h1 style={{color:"brown"}}>blog1 is here</h1>
              <p style={{fontSize:'20px'}}>This is blog1</p>
              <button className={styles.btn}>read more</button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
